global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['gss_local.aglic.dz:9100', 'gss_adex.aglic.dz:9100']  # Node Exporter target

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['gss_local.aglic.dz:8081','gss_adex.aglic.dz:8081']  # cAdvisor target
